const providers = [
  {
    id: "willhaben",
    name: "Willhaben",
    baseUrl: "https://www.willhaben.at",
    regions: ["AT"],
    listingTypes: ["buy", "rent", "commercial", "new-build"],
    priority: 1,
    fetchStrategy: "html",
    notes: "Large generalist classifieds site; requires respectful crawling and session management.",
  },
  {
    id: "immobilienNet",
    name: "Immobilien.net",
    baseUrl: "https://www.immobilien.net",
    regions: ["AT"],
    listingTypes: ["buy", "rent", "new-build", "commercial"],
    priority: 1,
    fetchStrategy: "html",
    notes: "High-volume portal with consistent detail pages and pagination.",
  },
  {
    id: "immoscout24",
    name: "ImmoScout24 Austria",
    baseUrl: "https://www.immobilienscout24.at",
    regions: ["AT"],
    listingTypes: ["buy", "rent", "commercial"],
    priority: 1,
    fetchStrategy: "html",
    notes: "Austrian edition of Scout24; stable DOM and geolocation hints in metadata.",
  },
  {
    id: "immowelt",
    name: "Immowelt Austria",
    baseUrl: "https://www.immowelt.at",
    regions: ["AT"],
    listingTypes: ["buy", "rent", "new-build"],
    priority: 2,
    fetchStrategy: "html",
    notes: "Good filters for room counts and energy certificates; pagination includes page counts.",
  },
  {
    id: "wohnnet",
    name: "Wohnnet",
    baseUrl: "https://www.wohnnet.at",
    regions: ["AT"],
    listingTypes: ["buy", "rent", "new-build"],
    priority: 2,
    fetchStrategy: "html",
    notes: "Offers editorial content; listing pages include map widget coordinates.",
  },
  {
    id: "derStandard",
    name: "Der Standard Immobilien",
    baseUrl: "https://www.derstandard.at/immobilien",
    regions: ["AT"],
    listingTypes: ["buy", "rent", "new-build"],
    priority: 2,
    fetchStrategy: "html",
    notes: "Newspaper marketplace; ensure polite rate limiting.",
  },
  {
    id: "kurier",
    name: "Kurier Immobilien",
    baseUrl: "https://immo.kurier.at",
    regions: ["AT"],
    listingTypes: ["buy", "rent", "commercial"],
    priority: 3,
    fetchStrategy: "html",
    notes: "Regional focus with rich search filters and clear breadcrumbs for location mapping.",
  },
  {
    id: "sreal",
    name: "S REAL",
    baseUrl: "https://www.sreal.at",
    regions: ["AT"],
    listingTypes: ["buy", "rent", "new-build", "commercial"],
    priority: 1,
    fetchStrategy: "api",
    notes: "Bank-owned brokerage with partner feeds; best onboarded via official API or feed access.",
  },
  {
    id: "remax",
    name: "RE/MAX Austria",
    baseUrl: "https://www.remax.at",
    regions: ["AT"],
    listingTypes: ["buy", "rent", "commercial"],
    priority: 1,
    fetchStrategy: "api",
    notes: "Franchise network; APIs available to partners for structured listing data.",
  },
  {
    id: "findmyhome",
    name: "FindMyHome",
    baseUrl: "https://www.findmyhome.at",
    regions: ["AT"],
    listingTypes: ["buy", "rent", "new-build"],
    priority: 3,
    fetchStrategy: "html",
    notes: "Smaller but curated inventory; photo galleries load lazily, so account for dynamic images.",
  },
  {
    id: "bazar",
    name: "Bazar Immobilien",
    baseUrl: "https://www.bazar.at/immobilien",
    regions: ["AT"],
    listingTypes: ["buy", "rent"],
    priority: 4,
    fetchStrategy: "html",
    notes: "Classifieds portal; expect varied data quality and more manual normalization.",
  },
  {
    id: "tirol",
    name: "Tiroler Tageszeitung Immo",
    baseUrl: "https://immo.tt.com",
    regions: ["AT-T"],
    listingTypes: ["buy", "rent"],
    priority: 3,
    fetchStrategy: "html",
    notes: "Regional Tirol coverage; make sure to tag listings with state-level metadata.",
  },
  {
    id: "salzburg",
    name: "Salzburger Nachrichten Immo",
    baseUrl: "https://immo.sn.at",
    regions: ["AT-S"],
    listingTypes: ["buy", "rent", "commercial"],
    priority: 3,
    fetchStrategy: "html",
    notes: "Regional Salzburg coverage with clear breadcrumb trails for locality extraction.",
  },
  {
    id: "oe24",
    name: "Oe24 Immobilien",
    baseUrl: "https://immo.oe24.at",
    regions: ["AT"],
    listingTypes: ["buy", "rent"],
    priority: 4,
    fetchStrategy: "html",
    notes: "News portal classifieds; expect lighter metadata and higher duplication rates.",
  },
  {
    id: "wohnkrone",
    name: "Wohnkrone",
    baseUrl: "https://www.wohnkrone.at",
    regions: ["AT"],
    listingTypes: ["buy", "rent"],
    priority: 4,
    fetchStrategy: "html",
    notes: "Krone marketplace; verify robots.txt before crawling and throttle aggressively.",
  },
  {
    id: "engelVoelkers",
    name: "Engel & Völkers Austria",
    baseUrl: "https://www.engelvoelkers.com/en-at",
    regions: ["AT"],
    listingTypes: ["buy", "rent", "luxury"],
    priority: 2,
    fetchStrategy: "html",
    notes: "Premium brokerage with structured metadata and map embeds in listing pages.",
  },
  {
    id: "ehl",
    name: "EHL Immobilien",
    baseUrl: "https://www.ehl.at",
    regions: ["AT"],
    listingTypes: ["buy", "rent", "commercial"],
    priority: 2,
    fetchStrategy: "html",
    notes: "Commercial and residential focus; PDF exposés may need parsing for full details.",
  },
  {
    id: "rustler",
    name: "Rustler Immobilien",
    baseUrl: "https://www.rustler.eu/en/real-estate",
    regions: ["AT"],
    listingTypes: ["buy", "rent", "commercial"],
    priority: 3,
    fetchStrategy: "html",
    notes: "Boutique brokerage; small volume but high-quality metadata.",
  },
  {
    id: "justimmo",
    name: "JustImmo",
    baseUrl: "https://www.justimmo.at",
    regions: ["AT"],
    listingTypes: ["buy", "rent", "new-build"],
    priority: 1,
    fetchStrategy: "api",
    notes: "Proptech platform that offers XML/JSON feeds and partner APIs—ideal for structured imports.",
  },
  {
    id: "flatbee",
    name: "flatbee",
    baseUrl: "https://www.flatbee.at",
    regions: ["AT"],
    listingTypes: ["rent", "buy"],
    priority: 3,
    fetchStrategy: "html",
    notes: "Focus on fee-free rentals; listings include landlord contact preferences.",
  },
];

module.exports = providers;
